In [ ]:
# Importando librerias necesarias
import pandas as pd

In [11]:
# Carga de datos
rutas = {
    'clientes': '../data/raw/clientes.csv',
    'categorias': '../data/raw/categorias.csv',
    'productos': '../data/raw/productos.csv',
    'ventas': '../data/raw/ventas.csv',
    'metodos_pago': '../data/raw/metodos_pago.csv'
}

data = {nombre: pd.read_csv(ruta) for nombre, ruta in rutas.items()}

clientes, categorias, productos, ventas, metodos_pago = data.values()

In [39]:
# Primer vistazo a los datos

# Tabla 'clientes'
print("Tabla: Clientes")
print(30 * "-")
print(f"Dimensiones: {clientes.shape[0]} filas y {clientes.shape[1]} columnas")
print(30 * "-")
print(f"Tipos de Datos:\n{clientes.dtypes}")
print(30 * "-")
print(f"Resumen General: {clientes.info()}")
print(30 * "-")
print("Primeras filas:")
clientes.head()

Tabla: Clientes
------------------------------
Dimensiones: 326 filas y 6 columnas
------------------------------
Tipos de Datos:
ID_Cliente          int64
Nombre             object
Apellido           object
Email              object
Fecha_Resgistro    object
Región             object
dtype: object
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Cliente       326 non-null    int64
 1   Nombre           326 non-null    object
 2   Apellido         326 non-null    object
 3   Email            326 non-null    object
 4   Fecha_Resgistro  326 non-null    object
 5   Región           326 non-null    object
dtypes: int64(1), object(5)
memory usage: 15.4+ KB
Resumen General: None
------------------------------
Primeras filas:

,ID_Cliente,Nombre,Apellido,Email,Fecha_Resgistro,Región
0,1,Karisa,Cromett,kcromett0@imageshack.us,19/11/2023,Patagonia
1,2,Lenette,Seabert,lseabert1@yahoo.co.jp,07/05/2023,Patagonia
2,3,Buddy,Silverson,bsilverson2@howstuffworks.com,27/03/2023,Patagonia
3,4,Dan,Parkin,dparkin3@virginia.edu,26/10/2023,Buenos Aires
4,5,Conney,Cassella,ccassella4@who.int,31/03/2023,Centro

In [40]:
# Tabla 'Categorias'
print("Tabla: Categorias")
print(30 * "-")
print(f"Dimensiones: {categorias.shape[0]} filas y {categorias.shape[1]} columnas")
print(30 * "-")
print(f"Tipos de Datos:\n{categorias.dtypes}")
print(30 * "-")
print(f"Resumen General: {categorias.info()}")
print(30 * "-")
print("Primeras filas:")
categorias.head()

Tabla: Categorias
------------------------------
Dimensiones: 8 filas y 3 columnas
------------------------------
Tipos de Datos:
ID_Categoria     int64
Categoría       object
Descripción     object
dtype: object
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID_Categoria  8 non-null      int64
 1   Categoría     8 non-null      object
 2   Descripción   8 non-null      object
dtypes: int64(1), object(2)
memory usage: 324.0+ bytes
Resumen General: None
------------------------------
Primeras filas:

,ID_Categoria,Categoría,Descripción
0,1,Lácteos,"Productos lácteos frescos y procesados, como l..."
1,2,Carnicería,"Carnes frescas y procesadas, como carne de vac..."
2,3,Panadería,"Productos horneados frescos, como pan, factura..."
3,4,Frutas y Verduras,"Frutas y verduras frescas, locales e importada..."
4,5,Congelados,"Productos congelados, como papas fritas, empan..."

In [38]:
# Tabla 'productos'
print("Tabla: Productos")
print(30 * "-")
print(f"Dimensiones: {productos.shape[0]} filas y {productos.shape[1]} columnas")
print(30 * "-")
print(f"Tipos de Datos:\n{productos.dtypes}")
print(30 * "-")
print(f"Resumen General: {productos.info()}")
print(30 * "-")
print("Primeras filas:")
productos.head()

Tabla: Productos
------------------------------
Dimensiones: 38 filas y 5 columnas
------------------------------
Tipos de Datos:
ID_Producto         int64
Nombre_producto    object
Categoría          object
Precio_Unitario    object
Stock               int64
dtype: object
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Producto      38 non-null     int64
 1   Nombre_producto  38 non-null     object
 2   Categoría        38 non-null     object
 3   Precio_Unitario  38 non-null     object
 4   Stock            38 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1.6+ KB
Resumen General: None
------------------------------
Primeras filas:

   ID_Producto Nombre_producto Categoría Precio_Unitario  Stock
0            1           Leche   Lácteos           12,24   3327
1            2           Yogur   Lácteos            5,21   3358
2            3   Queso cremoso   Lácteos           17,23   3167
3            4   Queso rallado   Lácteos           19,23   2099
4            5         Manteca   Lácteos            5,65   4929

In [37]:
# Tabla 'ventas'
print("Tabla: Ventas")
print(30 * "-")
print(f"Dimensiones: {ventas.shape[0]} filas y {ventas.shape[1]} columnas")
print(30 * "-")
print(f"Tipos de Datos:\n{ventas.dtypes}")
print(30 * "-")
print(f"Resumen General: {ventas.info()}")
print(30 * "-")
print("Primeras filas:")
ventas.head()

Tabla: Ventas
------------------------------
Dimensiones: 3029 filas y 7 columnas
------------------------------
Tipos de Datos:
ID_Venta        int64
Fecha          object
ID_Cliente      int64
ID_Producto     int64
Cantidad        int64
Método_Pago     int64
Estado         object
dtype: object
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3029 entries, 0 to 3028
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_Venta     3029 non-null   int64
 1   Fecha        3029 non-null   object
 2   ID_Cliente   3029 non-null   int64
 3   ID_Producto  3029 non-null   int64
 4   Cantidad     3029 non-null   int64
 5   Método_Pago  3029 non-null   int64
 6   Estado       3029 non-null   object
dtypes: int64(5), object(2)
memory usage: 165.8+ KB
Resumen General: None
------------------------------
Primeras filas:

,ID_Venta,Fecha,ID_Cliente,ID_Producto,Cantidad,Método_Pago,Estado
0,919,31/01/2024,10,25,5,1,Completa
1,947,31/01/2024,106,5,1,4,Completa
2,1317,31/1/2024,235,25,3,3,Completa
3,1607,31/1/2024,114,15,5,1,Completa
4,2038,31/1/2024,132,2,5,4,Completa

In [41]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3029 entries, 0 to 3028
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_Venta     3029 non-null   int64
 1   Fecha        3029 non-null   object
 2   ID_Cliente   3029 non-null   int64
 3   ID_Producto  3029 non-null   int64
 4   Cantidad     3029 non-null   int64
 5   Método_Pago  3029 non-null   int64
 6   Estado       3029 non-null   object
dtypes: int64(5), object(2)
memory usage: 165.8+ KB

In [ ]:
# Tabla 'metodos_pago'
print("Tabla: Metodos de Pago")
print(30 * "-")
print(f"Dimensiones: {metodos_pago.shape[0]} filas y {metodos_pago.shape[1]} columnas")
print(30 * "-")
print(f"Tipos de Datos:\n{metodos_pago.dtypes}")
print(30 * "-")
print(f"Resumen General: {metodos_pago.info()}")
print(30 * "-")
print("Primeras filas:")
metodos_pago.head()

Tabla: Metodos de Pago
------------------------------
Dimensiones: 5 filas y 3 columnas
------------------------------
Tipos de Datos:
ID_Metodo       int64
Método         object
Descripción    object
dtype: object
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_Metodo    5 non-null      int64
 1   Método       5 non-null      object
 2   Descripción  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
Resumen General: None
------------------------------
Primeras filas:

,ID_Metodo,Método,Descripción
0,1,Efectivo,"Pago en dinero en efectivo, sin intermediarios..."
1,2,Tarjeta de Crédito,Pago con tarjetas emitidas por bancos y financ...
2,3,Tarjeta de Débito,Pago con tarjetas que debitán directamente de ...
3,4,Mercado Pago,Plataforma de pagos online que permite realiza...
4,5,Transferencia,Pago realizado a través de una transferencia d...